import type { Metadata } from "next";
import "./globals.css"; // Assuming you have a globals.css file

export const metadata: Metadata = {
  title: "My Numbers App", // You can change this title
  description: "Generated by create next app", // You can change this description
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
} 